version: 2

sources:
  - name: zara_sales
    schema: dbt_nk
    database: zara_sales_db
    tables:
      - name: zara_sales_raw


models:
  - name: stg_zara_sales
    description: "Staging model for Zara raw sales data"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: price_standardized
        tests:
          - not_null
      - name: sales_volume
        tests:
          - not_null

  - name: mart_sales_summary
    description: "Aggregated sales summary for Tableau dashboards"
